version: "2"
services:
  python:
    image:  bitnami/jupyter-base-notebook:latest
    restart: always
    ports:
        - 8888:8888
    command: ["tail", "-f", "/dev/null"]
    container_name: "tmp-jupyter"
    tty: true